# Generated by Django 4.1.4 on 2022-12-21 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_personal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faces',
            fields=[
                ('id_face', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='')),
                ('face_data', models.FileField(upload_to='')),
                ('pers_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.personal')),
            ],
            options={
                'verbose_name': 'Faces',
                'verbose_name_plural': 'Faces',
            },
        ),
    ]
