# Generated by Django 4.1.4 on 2022-12-21 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cameras'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateTimeStamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timedate', models.DateTimeField(auto_now_add=True)),
                ('cab_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cabinets')),
                ('cam_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cameras')),
                ('per_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.personal')),
            ],
            options={
                'verbose_name': 'DateTimeStamp',
                'verbose_name_plural': 'DateTimeStamp',
            },
        ),
    ]
