# Generated by Django 4.1.4 on 2022-12-21 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_datetimestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
    ]
