# Generated by Django 4.1.4 on 2022-12-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_personal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameras',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datetimestamp',
            name='direction',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cameras',
            name='in_pos',
            field=models.BooleanField(default=False),
        ),
    ]
